name: unihub-club-service

services:
  club-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: unihub-club-service
    ports:
      - "8002:8002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=8002
      - MONGO_URI=mongodb://mongo:27017/clubdb
      - JWT_SECRET=devsecret
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_CLIENT_ID=club-service
    depends_on:
      - mongo
      - kafka

  mongo:
    image: mongo:6
    container_name: unihub-club-mongo
    ports:
      - "27020:27017"
    volumes:
      - club_mongo_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: unihub-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: unihub-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  club_mongo_data: